# Generated by Django 3.2.5 on 2021-07-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psbo', '0002_auto_20210729_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
